server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tag?serverTimezone=UTC
    username: root
    password: Liwenlong.0328
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      table-prefix: "tbl_"
      id-type: auto
